### ISSUE TITLE
Approval of content

### ISSUE THREAD

**Issue by kfklein15** [CodeYourFuture/CYF-PD#18]
AS A PD Director
I WANT to be able to approve the final content
SO THAT the content creation process is smoother

**Acceptance criteria**
**Scenario: approval of blocks**
GIVEN a new block was created by a PD volunteer
WHEN the person with the "approval" role is happy with it
THEN they can publish the block.

**Comment by kfklein15** [comment]
I think this needs to be discussed in more details and more a/c created, I just added the basic one.

**Comment by SallyMcGrath** [comment]
BTW I made this last week

**Comment by kfklein15** [comment]
Thanks, will look at it next week.

**Comment by LaraHuzjan** [comment]
Thank you for this Sally, just some comments for Karen and you to see:
-good that this process is not on Kanban so there's less confusion
-we still keep the Word document as it's easier to comment and imo is more clear
-the person that makes the content uploads the content (preferably in a week's time)
-can we omit the "draft" part and just have "in review" (once uploaded by the content creator it's already in review) and "ready" (once one of us has reviewed it and if necessary made any changes)

**Comment by kfklein15** [comment]
@SallyMcGrath , let us know if you need anything else from us on this, and if @LaraHuzjan suggestions above make sense.

**Comment by SallyMcGrath** [comment]
It's hard to understand what the request is here. This comment has a series of points and refers to a Word document, an upload process, and then there's a final point which may or may not be directed at me. 

If you want me to build something for you, please ask for it clearly.

**Comment by kfklein15** [comment]
**Scenario: remove draft status** 
GIVEN I am on the Approval of the content board
WHEN I see the status
THEN I can only see "In Review" and "Ready"

**Scenario: show in review from uploaded blocks**
GIVEN a new block was created via the CMS PD platform
WHEN I am on the Approval of the content board
THEN I can see all blocks in the "In Review" column

**Scenario: ready columns**
GIVEN a new block was available for review
WHEN I approve the block
THEN it is moved to the "Ready" column

@SallyMcGrath , @LaraHuzjan and I worked on the scenarios for this. Let us know if you have any questions.

**Comment by SallyMcGrath** [comment]
@kfklein15 

This is a bit clunky in the preview branch -- I think possibly because it is in a branch. It's not super configurable and I think not worth writing a pile of JS to override the built in functions. Therefore I have simply hidden the draft column with CSS.

 I'm going to merge it and you guys tell me if you want it turned off.
