### ISSUE TITLE
Portfolio: Goal setting and planning

### ISSUE THREAD

**Issue by Barny-6** [CodeYourFuture/CYF-PD#32]
[Google doc](https://docs.google.com/document/d/1FgdxeL096snW8AfHOVM8LlngDqQSP6hIWNOk-g6lCzs/edit?usp=sharing)

Class Prep (30 mins)
Review goals for [portfolio module](https://module-graduates.codeyourfuture.io/how-does-this-work/portfolio-goals)
Reflect on and write down your own goals for the portfolio module and employment.

Ideas for Class Exercises (1 hour)
Collectively review goals and discuss the reasons behind the goals (revealing the value in creating a strong portfolio)

**Comment by Barny-6** [comment]
@kfklein15 is this correctly set up and can I have permission to assign things etc?

**Comment by kfklein15** [comment]
[Uploaded on CMS](https://cyf-pd.netlify.app/blocks/goal-setting-and-planning/readme/)

**Comment by kfklein15** [comment]
[PR to upload it to Curriculum](https://github.com/CodeYourFuture/curriculum/pull/360)

**Comment by LaraHuzjan** [comment]
@Barny-6 @kfklein15 just to check, prep has been uploaded and it's PR as well.
Day plan and Coursework are finished and still have to be uploaded?

**Comment by kfklein15** [comment]
This has all been done.
