### ISSUE TITLE
Add Portfolio Module to PD CMS

### ISSUE THREAD

**Issue by kfklein15** [CodeYourFuture/CYF-PD#33]
AS Head of Employability
I WANT TO use the PD CMS to load Portfolio content
SO THAT I can easily create AND update content.

**Acceptance criteria**

**Scenario: create blocks for Portfolio**
GIVEN I am creating a new block on the [PD CMS page](https://cyf-pd.netlify.app/admin/#/collections/blocks)
WHEN I select the module Portfolio
THEN this new block is visible on the [PD Curriciulum page](https://cyf-pd.netlify.app/modules/html-css/)

**Scenario: update blocks for Portfolio**
GIVEN I am viewing an existing Portfolio block on the [PD CMS page](https://cyf-pd.netlify.app/admin/#/collections/blocks)
WHEN I update the content
THEN this block content is visible on the [PD Curriculum page](https://cyf-pd.netlify.app/modules/html-css/)

**Comment by kfklein15** [comment]
@SallyMcGrath , is this something easy to be done?

**Comment by SallyMcGrath** [comment]
@kfklein15 done #34
