### ISSUE TITLE
Enter not working on PD CMS

### ISSUE THREAD

**Issue by kfklein15** [CodeYourFuture/CYF-PD#37]
**Steps to reproduce**
1. Copy [a text from a Google Doc](https://docs.google.com/document/d/1FgdxeL096snW8AfHOVM8LlngDqQSP6hIWNOk-g6lCzs/edit) with bullet points into the CMS
2. Numbered list OR bullet points will show out of order
3. Backspace one of the lines so you can adjust the bullet point
4. Press enter on the phrase you want to go to the next bullet point 

**Expected outcome**
Text is kept in the same line AND bullet point is created

**Current outcome**
The text doesn't go to the next line

**Images below of the steps:**

Step 1 - Text I copied
1. Review as a group what a SMART goal is and why it’s important by answering these questions as a group (2mins)
2. 1. What does the S.M.A.R.T stand for? 
   2. Why do we use this acronym to help set goals?

Step 2 - pasting text
![Image](https://github.com/CodeYourFuture/CYF-PD/assets/80272258/576e898d-4f8d-41cc-91ae-2b3769a98a04)

Step 3 - backspace
![Image](https://github.com/CodeYourFuture/CYF-PD/assets/80272258/a2766349-3eaa-497d-8531-ae1a26edcd50)

Step 4 - enter for the phrase to move
![Image](https://github.com/CodeYourFuture/CYF-PD/assets/80272258/9747f1ce-17e8-42b7-af6c-fb640b2f80e3)

**Comment by SallyMcGrath** [comment]
@kfklein15 I cannot reproduce this problem. I followed the steps you gave (thank you) and the list was in order and I could update and change any aspect. Is this still happening for you?

**Comment by kfklein15** [comment]
It is still happening. I'll check our calendars to put something in place so I can show this to you.

**Comment by kfklein15** [comment]
This was solve with https://github.com/CodeYourFuture/CYF-PD/pull/42
