### ISSUE TITLE
Fundamentals Week 1: Importance of Professional Development section is confusing about "boards"

### ISSUE THREAD

**Issue by illicitonion** [CodeYourFuture/CYF-PD#5]
On https://cyf-curriculum.netlify.app/fundamentals/sprints/1/day-plan/ (content in https://github.com/CodeYourFuture/CYF-PD/blob/main/content/blocks/fundamentals-test/readme.md), the references to "board"s is a bit confusing.

In general we've been referring to "boards" to mean people's planning boards. I'm not sure from reading this whether the expectation is that trainees will end up with issues on their planning boards, or whether "boards" here is referring to the interactive whiteboard used in the online variant of this class (if so, the idea of using multiple boards wasn't really discussed).

Could we reword to make the following sentences more clear:
* "Make sure you are adding at least one ticket for each board." (what tickets / boards is this referring to)
* "Brainstorm the characteristics of the “Worst Boss” and add tickets to the board." (I think this is referring to the paper/whiteboard?)
* "Now think about the characteristics of the best boss you ever had or you would want to have and add them to the board." (as above)
* "Look at the Best Boss circle and group the ‘hard skills’ (technical skills) and the ‘soft skills’ (professional skills) on the board." (as above, and particularly, if we're doing this on paper, _how_? Maybe we should reframe the wording to talk about using post-its (which may be digital or physical)?

/cc @kfklein15 @esma-g

**Comment by esma-g** [comment]
I don't know how to edit the new curriculum yet, so I'm rewriting the above sentences in case it helps the editor:

- Make sure you have at least one contribution during each part of the exercise
- Think about the characteristics of the "Worst Boss", write your ideas on post-its and share them on the collaborative sheet
- Now think about the characteristics of the "Best Boss" you have ever had or you would want to have, write your ideas on post-its and share them on the collaborative sheet
- Work with your cohort to group the ‘hard skills’ (technical skills) and the ‘soft skills’ (professional skills) shared for the "Best Boss". You can move the post-its under these two headings on a separate sheet

**Comment by illicitonion** [comment]
Thank! I'll quickly make those edits, and hopefully everyone will know how to edit things soon!

**Comment by kfklein15** [comment]
Let me know if I need to do anything on this or if it has been done, please :)
